### ISSUE TITLE
Feature request: `prefer-vi-mocked`

### ISSUE THREAD

**Issue by me4502** [vitest-dev/eslint-plugin-vitest#443]
This rule would require access to TypeScript types, so unsure if this fits into the scope of the plugin.

Basically my request is a rule called something like `prefer-vi-mocked`, that prefers usage of `vi.mocked(thing)` over `(thing as Mock)`. The `vi.mocked` utility retains type information of the underlying mocked object, allowing proper type checking on function arguments and return types. Casting instead to `Mock` loses that information, and prevents type safety when mocking implementation or return value.

**Comment by veritem** [comment]
We do have other rules that depend on the type of information. If you want to implement this, a pr is welcome.
