### ISSUE TITLE
Async `describe` should not be an error

### ISSUE THREAD

**Issue by matyasf** [vitest-dev/eslint-plugin-vitest#511]
`vitest` supports async describe, see https://github.com/vitest-dev/vitest/issues/703#issuecomment-1038925412 and https://github.com/vitest-dev/vitest/pull/750

So this rule should be modified to support `async` https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/valid-describe-callback.md

**Comment by veritem** [comment]
a pr is welcome :D

**Comment by azu** [comment]
I've created a PR 

- https://github.com/vitest-dev/eslint-plugin-vitest/pull/517
