### ISSUE TITLE
New rule: `no-only`

### ISSUE THREAD

**Issue by GNRSN** [vitest-dev/eslint-plugin-vitest#516]
Essentially [eslint-plugin-no-only-tests](https://www.npmjs.com/package/eslint-plugin-no-only-tests) for vitest, prevent accidentally running `it.only`, `describe.only` etc in CI

**Comment by veritem** [comment]
a pr is welcome

**Comment by GNRSN** [comment]
Starting on a PR and looking through tests I realized this already exists as [no-focused-tests](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-focused-tests.md). 

I was just confused by the naming 😄
