### ISSUE TITLE
vitest/valid-describe-callback does not support options as second parameter

### ISSUE THREAD

**Issue by maxnowack** [vitest-dev/eslint-plugin-vitest#542]
Vitest v1.3.0 has deprecated the use of options as the last parameter in `describe` (https://github.com/vitest-dev/vitest/pull/5142).
The eslint plugin forces the second parameter of `describe` to be a function. Therefore the linter will fail if the options are passed as the second parameter

**Comment by veritem** [comment]
a pr is welcome!
