### ISSUE TITLE
[docs] Legacy rules are prepended with "@", but it is not in the docs

### ISSUE THREAD

**Issue by gndelia** [vitest-dev/eslint-plugin-vitest#566]
When using the newest Eslint configuration, rules are prefixed with `vitest/*`. For example: `vitest/no-conditional-expect`.  
However, for the legacy configuration, rules are prefixed with `@vitest/*`. For example: `@vitest/no-conditional-expect`.  

This is not documented anywhere. The readme only mentions the `vitest/`  prefix, which causes an error that rules can't be found when using the legacy config. I think while the legacy config is supported and documented, there should be a mention that rules are named differently. I only found out about this once I checked the code.

**Comment by veritem** [comment]
It's documented clearly on the readme.

**Comment by gndelia** [comment]
@veritem  thanks for your answer. It may be my limited knowledge of Eslint, but the only rule shown on the README is `vitest/max-nested-describe`. How can I deduce from that that if using the legacy option, it should be prefixed with `@` ? Can you point to the line where it is clearly on the readme?
