### ISSUE TITLE
Definition for rule 'vitest/no-disabled-tests' was not found

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vitest-dev/eslint-plugin-vitest#570]
Hello, migrating from https://www.npmjs.com/package/eslint-plugin-vitest to this one, and I noticed a lot of issues like `Definition for rule 'vitest/no-disabled-tests' was not found`

I checked docs and I can see `https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-disabled-tests.md` rule.

Also I see that recommended rules are applied, so plugin is loaded, like `warning  use test file name pattern .*\.test\.[tj]sx?$ @vitest/consistent-test-filename`

Turns out that docs say `vitest/no-disabled-tests` but the actual rule name is `@vitest/no-disabled-tests`, with at (@) in the beginning.

I think pretty much all rules docs are affected, please consider doing mass find-and-replace thingy, thank you!

**Comment by veritem** [comment]
@Maxim-Mazurok how does your eslint config look like? are you using flat config?

**Comment by Maxim-Mazurok** [comment]
Nope, I'm using the legacy format for now, and follow your instructions for legacy format.

**Comment by veritem** [comment]
I'm unable to reproduce why it's not working for you. Remember to use `legacy-recommended` or `legacy-all` in your configurations too.

**Comment by Maxim-Mazurok** [comment]
Ah, let me clarify what the issue is:
On this page: https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-disabled-tests.md
It says that the rule name is `vitest/no-disabled-tests` (without `@` in the beginning)
But here all the rules are defined with `@` in the front: https://github.com/vitest-dev/eslint-plugin-vitest/blob/6b213d0817e24d97639d4a3165b2382752be446f/src/index.ts#L81
So I should be using `@vitest/no-disabled-tests` (with at sign).
And this is different from the documentation, where rules don't include `@`, like here: https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-disabled-tests.md
So you see, I'm not reporting a problem with recommended/all configs, I'm reporting issue with documentation, because actual rules have different names.
Does it make more sense now?

**Comment by veritem** [comment]
Ooh so the docs assumes you're using the new flat config, since it's now the default configuration in eslint. That's what we recommend

**Comment by Maxim-Mazurok** [comment]
Ah, so for legacy config it's `@vitest/*` and for flat config it's `vitest/*`, got it... Would be great to specify in docs, but yeah, I'll move to flat config soon-ish anyway, cheers!
