### ISSUE TITLE
Enhance "all" configuration and update documentation

### ISSUE THREAD

**Issue by y-hsgw** [vitest-dev/eslint-plugin-vitest#577]
I noticed that the current "all" configuration does not apply all the available rules in eslint-plugin-vitest. For example, rules like expect-expect and no-commented-out-tests are not enabled when using `vitest.configs.all.rules`（`"plugin:vitest/all"`）.

Would it be acceptable to update the "all" configuration to include all rules by default?

Additionally, I would like to suggest adding documentation for the "all" configuration to the README, similar to the example provided in [eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest#all).

Please let me know your thoughts. I'm happy to help with these updates if needed!

Thank you for your time and consideration.🚀

**Comment by veritem** [comment]
We used to have documentation for it, but I removed it when we were doing migration to flat config. A pr is always welcome :D
