### ISSUE TITLE
Proposal: Add a Code Formatter

### ISSUE THREAD

**Issue by y-hsgw** [vitest-dev/eslint-plugin-vitest#597]
I propose introducing a code formatter, such as Prettier, to ensure consistent code style across the project.
If this sounds reasonable, I can help with the initial setup and configuration of Prettier (or any other preferred formatter). 
Let me know your thoughts!😄

**Comment by veritem** [comment]
I have https://eslint.style/ setup with default configs. Did you find inconsistency anywhere in the repo?

**Comment by y-hsgw** [comment]
Got it!
It might be possible that the formatting only applies to the `.js` files.
I think it would be a good idea to apply it to `.ts` files as well. What do you think?

**Comment by veritem** [comment]
Does it only format `.js` files only? It should be both.

**Comment by y-hsgw** [comment]
Yes, it seems to be applied only to `.js` files.

For example, when running [lint:js](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/package.json#L34), I believe the following link should trigger an [@stylistic/quotes](https://eslint.style/rules/default/quotes) error, but it doesn't seem to happen:

https://github.com/vitest-dev/eslint-plugin-vitest/blob/342ce00735efae20b94d2027738ffcc2d88c069d/src/utils/ast-utils.ts#L1-L2
