### ISSUE TITLE
`vitest/expect-expect` throws false positive in v1.1.18

### ISSUE THREAD

**Issue by dirkluijk** [vitest-dev/eslint-plugin-vitest#603]
In `1.1.18` of `@vitest/eslint-plugin`, there seems to be a regression in the `vitest/expect-expect` rule, which doesn't seem present in `1.1.17` or lower.

## Reproduction

Go to https://stackblitz.com/edit/vitejs-vite-spv6ulzt?file=package.json
Run `npm run lint` in console

You see `8:38  error  Test has no assertions  vitest/expect-expect`, whereas an assertion is present.

## Environment
TypeScript 5.7
ESLint 9.17.0
typescript-eslint 8.18.1

**Comment by veritem** [comment]
@y-hsgw could you check you changes in #600 I think there is a bug around this diff https://github.com/vitest-dev/eslint-plugin-vitest/pull/600/files#diff-5e10d81f15e90dc8a24d75b57d5f24879b3b80a6eec3adb8ae699e8bb1030f0eL255-L256 

do you mind having a look?
